# Generated by Django 5.2.4 on 2025-08-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tweets', '0002_tweet_created_at_tweet_updated_at_tweet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tweets.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
